# https://docs.astro.build/en/guides/deploy/deno/

name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install --allow-scripts

      - name: Check linting
        run: deno lint

      - name: Check formatting
        run: deno fmt --check

      - name: Build Astro
        run: deno run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: d-astro
          entrypoint: server/entry.mjs # SSR
          # entrypoint: jsr:@std/http/file-server # Static
          root: dist
